### ISSUE TITLE
Reported an error

### ISSUE THREAD

**Issue by maiqunshan** [TTPlanetPig/Comfyui_JC2#15]
# ComfyUI Error Report
## Error Details
- **Node ID:** 63
- **Node Type:** JoyCaption2_simple
- **Exception Type:** TypeError
- **Exception Message:** object of type 'NoneType' has no len()
## Stack Trace
```
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)

  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])

```
## System Information
- **ComfyUI Version:** v0.3.5-8-gbf2650a
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu118
## Devices

I have re-downloaded the model, but the error still occurs

**Comment by maiqunshan** [comment]
After updating comfyui, an error was reported.

**Comment by maiqunshan** [comment]
got prompt
comfy_model_dir: C:\ComfyUI_MAI\ComfyUI\models\LLM
Start to load existing model on cuda:0
Free VRAM: 14.74 GB
Start to load existing VLM
Loading in NF4
Loading CLIP
Error loading models: Couldn't build proto file into descriptor pool: duplicate file name sentencepiece_model.proto
Error loading model: local variable 'clip_processor' referenced before assignment
!!! Exception during processing !!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'NoneType' has no len()

Prompt executed in 0.05 seconds

**Comment by maiqunshan** [comment]
got prompt
comfy_model_dir: C:\ComfyUI_MAI\ComfyUI\models\LLM
Start to load existing model on cuda:0
Free VRAM: 14.74 GB
Free VRAM is less than 20GB when loading 'bf16' model. Performing VRAM cleanup.
Start to load existing VLM
Loading in bfloat16
Loading CLIP
Error loading models: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error loading model: local variable 'clip_processor' referenced before assignment
!!! Exception during processing !!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'NoneType' has no len()

Prompt executed in 0.48 seconds

**Comment by maiqunshan** [comment]
got prompt
comfy_model_dir: C:\ComfyUI_MAI\ComfyUI\models\LLM
Start to load existing model on cuda:0
Free VRAM: 14.74 GB
Start to load existing VLM
Loading in NF4
Loading CLIP
Error loading models: Couldn't build proto file into descriptor pool: duplicate file name sentencepiece_model.proto
Error loading model: local variable 'clip_processor' referenced before assignment
!!! Exception during processing !!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'NoneType' has no len()

Prompt executed in 0.06 seconds

**Comment by smuelpeng** [comment]
same error on ComfyUI V0.20.0 and V0.36.0

**Comment by Kallamamran** [comment]
Same error :(

```
ComfyUI (Embedded): v0.3.7
ComfyUI_frontend: v1.4.13
Python Version: 3.11.9
Pytorch Version: 2.5.1+cu124
```

![image](https://github.com/user-attachments/assets/a7716b33-8f24-49b8-9ea8-cf38e074b696)

```
Prompt executed in 1.32 seconds
got prompt
comfy_model_dir: C:\ComfyUI_windows_portable\ComfyUI\models\LLM
Start to load existing model on cuda:0
Free VRAM: 14.62 GB
Free VRAM is less than 20GB when loading 'bf16' model. Performing VRAM cleanup.
Start to load existing VLM
Loading in bfloat16
Loading CLIP
Loading tokenizer
Error loading models: Incorrect path_or_model_id: 'C:\ComfyUI_windows_portable\ComfyUI\models\Joy_caption\cgrkzexw-599808\text_model'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Error loading model: cannot access local variable 'tokenizer' where it is not associated with a value
!!! Exception during processing !!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 229, in get_output_data
    output = merge_result_data(results, obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 176, in merge_result_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by EricRollei** [comment]
I have the same error.  I think it's related to the version of transformers.  Requirements specify a range transformers>=4.43.2,<=4.45.1  but of course many other custom nodes may need a newer version like 4.47
